project:
  type: website
  output-dir: docs

website:
  title: "me.log"
  navbar:
    background: "#3A2240"
    foreground: "#F0ECF5"
    right:
      - href: posts/index.qmd
        text: "/posts"
      - href: publications/index.qmd
        text: "/publications"
      - href: projects/index.qmd
        text: "/projects"
      - href: about/index.qmd
        text: "/about"
    tools:
      - icon: github
        href: https://github.com/gabrielvpina
  page-footer:
    center: "© gabriel_pina :: 2026"
    border: false
    background: "#3A2240"
    foreground: "#B08AB0"

format:
  html:
    theme: flatly
    css: styles/retro.css
    toc: false
    fontsize: 0.9em
    resources:
      - assets/

execute:
  freeze: true
